#!/bin/bash
yum update -y
yum install -y httpd.x86_64
systemctl start httpd.service
systemctl enable http.service
echo "Aplicação criada na conta aws com IP: $(hostname -f)" / > /var/www/html/index.html
